# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonardo Viana Casasanta
title: Mobile Software Engineer
email: leonardo2050@gmail.com
website: www.github.com/leonvian/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: leonvian
linkedin_username: leonardo-casasanta-92bb2220

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Leonardo and I'm a Mobile Software Engineer. I have extensive experience developing innovative mobile solutions with a focus on quality and performance.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/leonvian
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully-fledged app. I have learned many skills through this and am very proud of having this in my portfolio.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mobile Software Engineer
        link: utility.com
        sub_title: Utility (2022 - Present)
        description: | # this will include new lines to allow paragraphs
          **Pliability**: Handled Android development, revamped UI, fixed Crashlytics issues, and upgraded Player library.
          **Counslr**: Refactored legacy app, added repository layer, reduced API calls, and rebranded UI.
          **Colorchain**: Built UI, API integrations, and Shopify connections from scratch.
          **Care**: Developed reusable Android UI library with Jetpack Compose, led work profile module refactoring, and improved accessibility.

      - layout: left
        title: Mobile Software Engineer
        link: arctouch.com
        sub_title: ArcTouch (2018 - 2022)
        description: | # this will include new lines to allow paragraphs
          **3M Filtrete**: Overhauled Bluetooth module and improved Google Play rating.
          **Flavor Maker by McCormick**: Developed features, including "recipe battle," and ensured accessibility compliance.
          **Quizlet**: Maintained app, fixed bugs, and delivered features improving performance metrics.

      - layout: left
        title: Mobile Software Engineer
        link: primesystems.com
        sub_title: Prime Systems (2013 - 2018)
        description: | # this will include new lines to allow paragraphs
          Revamped UI module of flagship product and introduced new features, including trace routes using Google Maps. Defined patterns and technologies for company products.

      - layout: left
        title: Mobile Software Engineer
        link: algar.com
        sub_title: Algar (2010 - 2013)
        description: | # this will include new lines to allow paragraphs
          **Aedes aegypti Control**: Developed Java ME app for health workers tracking mosquito breeding sites.
          **SIF**: Lead developer for Android app enabling health inspectors to monitor restaurants, including Bluetooth printer integration.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Post-graduate Specialization
        sub_title: Strategies in Software Architecture
        caption: IGTI – Institution of Management Technology, Belo Horizonte, Brazil (Mar/2012 - Mar/2013)

      - layout: left
        title: Bachelor of Computer Science
        sub_title: FACSAL - Santa Luzia College, Santa Luzia, Brazil
        caption: (Feb/2008 - Dec/2011)

      - layout: left
        title: Technical Management Computing
        sub_title: COTEMIG, Belo Horizonte, Brazil
        caption: (Feb/2005 - Dec/2007)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mobile software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Cooking
      - [Exploring new technologies](https://www.github.com/leonvian)

      Look at this cool image
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
