# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leonardo Viana Casasanta
title: Mobile Software Engineer
email: leonardo2050@gmail.com
website: www.github.com/leonvian/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: leonvian
linkedin_username: leonardo-casasanta-92bb2220

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Leonardo and I'm a Mobile Software Engineer. I have extensive experience developing innovative mobile solutions with a focus on quality and performance.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pliability - Top Marketing Fit App
        link: https://github.com/leonvian/pliability
        description: |
          I handled all Android development tasks, including rebuilding most of the UI following design and product team guidelines. I fixed and enhanced issues identified via Crashlytics and analytics, revamped payment screens, implemented the app's most popular features from scratch, and upgraded the Player library to the latest version.
          Technologies: Android ExoPlayer, coroutines, Room (SQLite), Retrofit (REST), Android Navigation, Google Play Billing.
        images:
          - images/pliability/screenshot1.png
          - images/pliability/screenshot2.png
          - images/pliability/screenshot3.png

      - layout: left
        title: Counslr - Therapy App
        link: https://github.com/leonvian/counslr
        description: |
          As the sole Android developer, I worked extensively on refactoring this legacy app, which had significant crashes and memory leaks. I introduced a repository layer using Retrofit and SQLite to reduce unnecessary API calls, rebranded the app, and redesigned 90% of its UI.
          Technologies: SendBird (chat framework), GraphQL, SQLite (Room).
        images:
          - images/counslr/screenshot1.png
          - images/counslr/screenshot2.png

      - layout: left
        title: Colorchain - E-commerce App
        link: https://github.com/leonvian/colorchain
        description: |
          I rebuilt this abandoned app from scratch, creating its UI, API integrations, and core functionality. I implemented seamless connections with the Shopify API for product data and payment processing.
          Technologies: Shopify API integration.
        images:
          - images/colorchain/screenshot1.png
          - images/colorchain/screenshot2.png

      - layout: left
        title: Care - Caregiver Job Matching App
        link: https://github.com/leonvian/care
        description: |
          This was a large-scale project with a multidisciplinary team spread across the globe. I developed a reusable Android UI library using Jetpack Compose, creating shareable components. Additionally, I led a refactoring of the work profile module and contributed to initiatives aimed at improving accessibility for users with disabilities.
          Technologies: Jetpack Compose, accessibility components.
        images:
          - images/care/screenshot1.png
          - images/care/screenshot2.png

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
